name: Collect Metadata

on:
  schedule:
    - cron: "00 12 * * *"

jobs:
  update:
    name: Count remaining Buzzsumo API calls
    runs-on: ubuntu-latest
    env:
      BUZZSUMO_TOKEN: ${{ secrets.BUZZSUMO_TOKEN }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pybadges

      - name: Update JSON data
        run: python defacto-enrichment/badge/generate.py

      - name: Commit data
        run: |
          if git diff defacto-enrichment/badge | grep . > /dev/null ; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git pull
            git commit -m "update badge" defacto-enrichment/badge
            git push
          fi
